SELECT
	ORDERS.ORDER_ID,
	CUSTOMERS.COMPANY_NAME,
	EMPLOYEES.FIRST_NAME,
	EMPLOYEES.LAST_NAME
FROM
	ORDERS
	INNER JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
	INNER JOIN CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
	INNER JOIN EMPLOYEES ON ORDERS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
ORDER BY
	ORDERS.ORDER_ID;