SELECT
	PRODUCTS.PRODUCT_ID,
	PRODUCTS.PRODUCT_NAME,
	CATEGORIES.CATEGORY_NAME,
	SUPPLIERS.COMPANY_NAME AS SUPPLIER
FROM
	PRODUCTS
    INNER JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID
    INNER JOIN SUPPLIERS ON PRODUCTS.SUPPLIER_ID = SUPPLIERS.SUPPLIER_ID
ORDER BY
	PRODUCTS.PRODUCT_ID;