SELECT
	CUSTOMERS.CUSTOMER_ID,
	CUSTOMERS.COMPANY_NAME,
	COUNT(ORDERS.CUSTOMER_ID) AS TOTAL_ORDERS
FROM
	CUSTOMERS
	INNER JOIN ORDERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
GROUP BY
	CUSTOMERS.CUSTOMER_ID,
	CUSTOMERS.COMPANY_NAME
ORDER BY
	CUSTOMERS.CUSTOMER_ID;