SELECT
	EMPLOYEES.FIRST_NAME,
	EMPLOYEES.LAST_NAME,
	ROUND(
		SUM(
			ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * (1 - ORDER_DETAILS.DISCOUNT)
		)::NUMERIC,
		2
	) AS TOTAL_PRICE
FROM
	ORDER_DETAILS
	JOIN ORDERS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
	JOIN EMPLOYEES ON ORDERS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
WHERE
	ORDERS.SHIPPED_DATE IS NOT NULL
GROUP BY
	EMPLOYEES.FIRST_NAME,
	EMPLOYEES.LAST_NAME
ORDER BY
	EMPLOYEES.FIRST_NAME;