SELECT
	CATEGORIES.CATEGORY_ID,
	CATEGORIES.CATEGORY_NAME,
	ROUND(AVG(PRODUCTS.UNIT_PRICE)) AS AVERAGE_PRICE
FROM
	PRODUCTS
	JOIN CATEGORIES ON PRODUCTS.CATEGORY_ID = CATEGORIES.CATEGORY_ID
GROUP BY
	CATEGORIES.CATEGORY_ID,
	CATEGORIES.CATEGORY_NAME,
	PRODUCTS.CATEGORY_ID
ORDER BY
	PRODUCTS.CATEGORY_ID;