SELECT
    ORDERS.ORDER_ID,
    CUSTOMERS.COMPANY_NAME,
    EMPLOYEES.FIRST_NAME,
    EMPLOYEES.LAST_NAME
FROM
    ORDERS
JOIN 
    ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
JOIN
    CUSTOMERS ON ORDERS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
JOIN
    EMPLOYEES ON ORDERS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID;
